export enum ACTIONS_SOCKET {
  JOIN = 'JOIN',
  LEAVE = 'LEAVE',
  ADD_PEER = 'ADD_PEER',
  REMOVE_PEER = 'REMOVE_PEER',
  RELAY_SDP = 'REPAY_SDP',
  RELAY_ICE = 'RELAY_ICE',
  ICE_CANDIDATE = 'ICE_CANDIDATE',
  SHARE_USER = 'SHARE_USER',
  NUMBER_OF_CONNECTIONS = 'NUMBER_OF_CONNECTIONS',
  USER_CONNECTED = 'USER_CONNECTED',
  TOGGLE_AUDIO = 'TOGGLE_AUDIO',
  TOGGLE_VIDEO = 'TOGGLE_VIDEO',
}
