import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import '@styles/globals.css';
import Providers from '@layouts/Providers';
import 'react-spring-bottom-sheet/dist/style.css';

const manrope = Manrope({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${manrope.className} antialiased`}>{children}</body>
      </Providers>
    </html>
  );
}
